version: '3'

services:
  envoy:
    image: envoyproxy/envoy:v1.9.0
    volumes:
      - ./sidecar/envoy.yaml:/etc/envoy/envoy.yaml
      - ./sidecar/config:/etc/envoy/config/
    expose:
      - "8080"
      - "8001"
    ports:
      - "8080:8080"
      - "8001:8001"

  echo:
    build: python-server
    environment: 
      - GRPC_VERBOSITY=debug
    volumes:
      - ./python-server:/app
    ports:
     - "9000:9000"